import './globals.css'
import type { Metadata } from 'next'
import { Figtree  } from 'next/font/google'
import Sidebar from '../components/Sidebar'
import SupabaseProvider from '@/providers/SupabaseProvider'
import UserProvider from '@/providers/UserProvider'
import ModalProvider from '@/providers/ModalProvider'
const font = Figtree({ subsets: ['latin'] })
import ToasterProvider from '@/providers/ToasterProvider'

export const metadata: Metadata = {
  title: 'Spotify clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider/>
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider/>
          <Sidebar>
        {children}
          </Sidebar>
          </UserProvider>
       
        </SupabaseProvider>
        </body>
    </html>
  )
}
